services:
  flagr:
    image: ghcr.io/openflagr/flagr:latest
    ports:
      - "18000:18000"
    environment:
      - FLAGR_DB_DSN=postgres://flagr:flagr@postgres:5432/flagr?sslmode=disable
      - FLAGR_REDIS_HOST=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flagr
      POSTGRES_PASSWORD: flagr
      POSTGRES_DB: flagr
    volumes:
      - flagr_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - flagr


  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
    depends_on:
      - api

volumes:
  flagr_postgres_data: